title: "Erasitexnis"
description: >-
  Personal website of artist Aristeidis Apladas - Προσωπική ιστοσελίδα του καλλιτέχνη Αριστείδη Απλαδά
subtitle: "Aristeidis Apladas"
domain: erasitexnis.github.io
url: https://erasitexnis.github.io
name: erasitexnis
real_name: "Aristeidis Apladas"
github_username:  erasitexnis
repository: "erasitexnis/erasitexnis.github.io"

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#paginate: 5
minimal_mistakes_skin: "dirt"
#locale: "en"
logo: "/assets/about/erasitexnis.100.jpg"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: erasitexnis
      read_time: false
      comments: false
      share: false
      related: false
      show_date: false
      author_profile: false